users = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    age: 32,
    gender: "Male",
  },
  {
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    age: 28,
    gender: "Female",
  },
  {
    name: "Michael Williams",
    email: "michael.williams@example.com",
    age: 45,
    gender: "Male",
  },
  {
    name: "Jessica Brown",
    email: "jessica.brown@example.com",
    age: 35,
    gender: "Female",
  },
  {
    name: "Christopher Jones",
    email: "christopher.jones@example.com",
    age: 23,
    gender: "Male",
  },
  {
    name: "Amanda Davis",
    email: "amanda.davis@example.com",
    age: 29,
    gender: "Female",
  },
  {
    name: "Daniel Rodriguez",
    email: "daniel.rodriguez@example.com",
    age: 38,
    gender: "Male",
  },
  {
    name: "Sarah Martinez",
    email: "sarah.martinez@example.com",
    age: 31,
    gender: "Female",
  },
  {
    name: "Matthew Taylor",
    email: "matthew.taylor@example.com",
    age: 27,
    gender: "Male",
  },
  {
    name: "Ashley Jackson",
    email: "ashley.jackson@example.com",
    age: 40,
    gender: "Female",
  },
  {
    name: "David Thompson",
    email: "david.thompson@example.com",
    age: 34,
    gender: "Male",
  },
  {
    name: "Jennifer White",
    email: "jennifer.white@example.com",
    age: 26,
    gender: "Female",
  },
  {
    name: "James Harris",
    email: "james.harris@example.com",
    age: 37,
    gender: "Male",
  },
  {
    name: "Jessica Lee",
    email: "jessica.lee@example.com",
    age: 33,
    gender: "Female",
  },
  {
    name: "Ryan Clark",
    email: "ryan.clark@example.com",
    age: 30,
    gender: "Male",
  },
  {
    name: "Lauren Lewis",
    email: "lauren.lewis@example.com",
    age: 39,
    gender: "Female",
  },
  {
    name: "Justin King",
    email: "justin.king@example.com",
    age: 25,
    gender: "Male",
  },
  {
    name: "Melissa Walker",
    email: "melissa.walker@example.com",
    age: 41,
    gender: "Female",
  },
  {
    name: "Andrew Green",
    email: "andrew.green@example.com",
    age: 36,
    gender: "Male",
  },
  {
    name: "Stephanie Hall",
    email: "stephanie.hall@example.com",
    age: 24,
    gender: "Female",
  },
  {
    name: "Joshua Baker",
    email: "joshua.baker@example.com",
    age: 42,
    gender: "Male",
  },
  {
    name: "Rachel Adams",
    email: "rachel.adams@example.com",
    age: 32,
    gender: "Female",
  },
  {
    name: "Brandon Wright",
    email: "brandon.wright@example.com",
    age: 28,
    gender: "Male",
  },
  {
    name: "Nicole Hill",
    email: "nicole.hill@example.com",
    age: 43,
    gender: "Female",
  },
  {
    name: "Kevin Nelson",
    email: "kevin.nelson@example.com",
    age: 31,
    gender: "Male",
  },
  {
    name: "Kimberly King",
    email: "kimberly.king@example.com",
    age: 27,
    gender: "Female",
  },
  {
    name: "Jason Rivera",
    email: "jason.rivera@example.com",
    age: 44,
    gender: "Male",
  },
  {
    name: "Hannah Cooper",
    email: "hannah.cooper@example.com",
    age: 29,
    gender: "Female",
  },
  {
    name: "Brian Ward",
    email: "brian.ward@example.com",
    age: 35,
    gender: "Male",
  },
  {
    name: "Megan Torres",
    email: "megan.torres@example.com",
    age: 26,
    gender: "Female",
  },
  {
    name: "Timothy Ramirez",
    email: "timothy.ramirez@example.com",
    age: 46,
    gender: "Male",
  },
  {
    name: "Victoria Reed",
    email: "victoria.reed@example.com",
    age: 30,
    gender: "Female",
  },
  {
    name: "Eric Brooks",
    email: "eric.brooks@example.com",
    age: 34,
    gender: "Male",
  },
  {
    name: "Samantha Morgan",
    email: "samantha.morgan@example.com",
    age: 25,
    gender: "Female",
  },
  {
    name: "Jeffrey Cox",
    email: "jeffrey.cox@example.com",
    age: 47,
    gender: "Male",
  },
  {
    name: "Maria Perry",
    email: "maria.perry@example.com",
    age: 31,
    gender: "Female",
  },
  {
    name: "Kyle Bailey",
    email: "kyle.bailey@example.com",
    age: 28,
    gender: "Male",
  },
  {
    name: "Amy Long",
    email: "amy.long@example.com",
    age: 48,
    gender: "Female",
  },
  {
    name: "Gregory Foster",
    email: "gregory.foster@example.com",
    age: 33,
    gender: "Male",
  },
  {
    name: "Angela Richardson",
    email: "angela.richardson@example.com",
    age: 27,
    gender: "Female",
  },
  {
    name: "Nicholas Cox",
    email: "nicholas.cox@example.com",
    age: 49,
    gender: "Male",
  },
  {
    name: "Rebecca Howard",
    email: "rebecca.howard@example.com",
    age: 32,
    gender: "Female",
  },
  {
    name: "Tyler Ward",
    email: "tyler.ward@example.com",
    age: 29,
    gender: "Male",
  },
  {
    name: "Christina Russell",
    email: "christina.russell@example.com",
    age: 50,
    gender: "Female",
  },
  {
    name: "Patrick Peterson",
    email: "patrick.peterson@example.com",
    age: 30,
    gender: "Male",
  },
  {
    name: "Christine Griffin",
    email: "christine.griffin@example.com",
    age: 34,
    gender: "Female",
  },
  {
    name: "Edward Butler",
    email: "edward.butler@example.com",
    age: 51,
    gender: "Male",
  },
  {
    name: "Tiffany Gonzalez",
    email: "tiffany.gonzalez@example.com",
    age: 31,
    gender: "Female",
  },
];

// console.log(users.length); // 48

module.exports = users;
